name: lovephim

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_lovephim
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lovePhim
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: redis_lovephim
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  minio:
    image: minio/minio:latest
    container_name: minio_lovephim
    restart: always
    ports:
      - "9000:9000"   # MinIO API (Spring Boot d√πng)
      - "9001:9001"   # MinIO Console (Web UI)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      TZ: Asia/Ho_Chi_Minh
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mysql_data:
  redis_data:
  minio_data:

